import "./globals.css";
import { Montserrat, Rubik } from "next/font/google";
import AuthProvider from "./providers/AuthProvider";
import NotistackProvider from "./providers/NotistackProvider";
import "react-toastify/dist/ReactToastify.css";

export const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  weight: ["500"],
  variable: "--font-rubik",
});

export const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Pindonga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${rubik.variable} font-sans`}>
        <NotistackProvider />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
